create table parsexmlpayment (
                                   id int4 generated by default as identity,
                                   fromPay varchar(255),
                                   toPay varchar(255),
                                   amount int4,
                                   primary key (id)
)